### ISSUE TITLE
isreal?

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaGeometry/Octonions.jl#11]
I do not understand how this makes sense.
```
isreal(o::Octonion) = iszero(o.v1) & iszero(o.v2) & iszero(o.v3) & iszero(o.v4) & iszero(o.v5) & iszero(o.v6) & iszero(o.v7)
```

**Comment by hyrodium** [comment]
Could you clarify your issue? Is there an alternative implementation for `isreal`?

**Comment by sethaxen** [comment]
> I do not understand how this makes sense.
> ```
> isreal(o::Octonion) = iszero(o.v1) & iszero(o.v2) & iszero(o.v3) & iszero(o.v4) & iszero(o.v5) & iszero(o.v6) & iszero(o.v7)
> ```
> 

I'm not sure I follow either. Iff the octonion is real, then the imaginary part must be zero.

**Comment by JeffreySarnoff** [comment]
misread
